version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: --init-file /data/application/init.sql
    ports:
      - "13306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
      - "./src/test/resources/init.sql:/data/application/init.sql"

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: exampleaccesskey
      MINIO_SECRET_KEY: examplesecretkey
    ports:
      - "19000:9000"
    volumes:
      - "miniodata:/data"
    command: server /data

volumes:
  dbdata:
  miniodata:
